### ISSUE TITLE
How's the running speed?

### ISSUE THREAD

**Issue by haikuoyao** [sercant/android-segmentation-app#1]
Hi,

This is an amazing project.

How many milliseconds cost per frame/image?
What device for testing?

Thanks a lot.

**Comment by sercant** [comment]
Hello @haikuoyao, sorry that I missed your issue.

Thank you and hope it's useful for you. The findings to the inference speed can be found in our paper at [doi:10.1007/978-3-030-20205-7_4](https://doi.org/10.1007/978-3-030-20205-7_4). If you are unable to read the springer paper, there is a preprint version at [arXiv](https://arxiv.org/abs/1902.07476).

Let me know if you have more questions.
